### ISSUE TITLE
Feature request: Negation

### ISSUE THREAD

**Issue by binary64** [kwaimind/eslint-plugin-prefix-types#2]
Hi I am the opposite - I do not want to allow IInterface, TType etc into my codebase. Could you support a negate: true?

**Comment by kwaimind** [comment]
Hey @binary64 yeah I can take a look into that.

**Comment by kwaimind** [comment]
@binary64 this has been added in v2 of the plugin. Check the readme for details on how to set negation :)

https://www.npmjs.com/package/eslint-plugin-prefix-types

**Comment by binary64** [comment]
Awesome! It works exactly as expected, thank you
