### ISSUE TITLE
Bug: eslint-ignore-next-line is not honored

### ISSUE THREAD

**Issue by binary64** [kwaimind/eslint-plugin-prefix-types#5]
I found a strange one:

![image](https://user-images.githubusercontent.com/1680627/150444316-1ab89445-065f-48ae-9696-a6019482396f.png)

The code I have is
```
// eslint-ignore-next-line prefix-types/prefer-interface-prefix
interface IMatch {
  text: string
  start: number
  end: number
}
```
and the eslintrc is
```
    "prefix-types/prefer-interface-prefix": ["error", { "allow": "never" }],
    "prefix-types/prefer-type-prefix": ["error", { "allow": "never" }],
    "prefix-types/prefer-styled-component-prefix": ["error", { "allow": "never" }],
```

**Comment by kwaimind** [comment]
`// eslint-disable-next-line prefix-types/prefer-interface-prefix` works for me. You're using `ignore` instead of `disable`. See [here](https://eslint.org/docs/2.13.1/user-guide/configuring#disabling-rules-with-inline-comments).

**Comment by binary64** [comment]
Thank you. Silly mistake!
